const CONFIG={vigia:"Daniel",urlApp:"https://script.google.com/macros/s/AKfycbyFgCjb1DRp_-TYMcQ6lqow_JlU9HWUvJpVULi36Syvb2POcYXjN7Cc8gAbYumhkUS_w/exec",dbName:"RomaneioDigitalDB",dbVersion:1,queueStore:"fila",eventStore:"eventos"};
const state={online:navigator.onLine,active:false,activeId:null,watchId:null,lastPosition:null,battery:null,manualUnlocked:false,ocrDocumentAttempted:false,ocrPlateAttempted:false,ocrDocumentSuccess:false,ocrPlateSuccess:false,fotoCarimbadaBase64:"",selfieTakenAt:null,db:null,ocrBusy:false,pageHiddenAt:null,exitContext:null,onboarding:{slide:Number(localStorage.getItem("rd_onboarding_slide")||1),done:localStorage.getItem("rd_onboarding_done")==="true",logs:JSON.parse(localStorage.getItem("rd_onboarding_logs")||"{}")}};
const $=id=>document.getElementById(id),now=()=>new Date(),human=()=>{const d=now();return{data:d.toLocaleDateString("pt-BR"),hora:d.toLocaleTimeString("pt-BR"),iso:d.toISOString()}};
function toast(msg,ms=2800){const el=$("toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),ms)}
function vibrar(p=30){try{navigator.vibrate?.(p)}catch{}}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id).classList.add("active");scrollTo({top:0,behavior:"instant"})}
function openOverlay(html,type="normal"){const box=$("overlayBox");box.className="modal"+(type==="danger"?" modal-danger":"");$("overlayBody").innerHTML=html;$("overlay").classList.add("show")}
function closeOverlay(){$("overlay").classList.remove("show")}
function setLoading(title,text="Processando..."){openOverlay(`<div class="loading-center"><div class="spinner"></div><h3>${title}</h3><p>${text}</p></div>`)}
function updateClock(){const d=now();$("topClock").textContent=d.toLocaleTimeString("pt-BR");$("topStatus").textContent=state.active?(state.online?"ATENDIMENTO • ONLINE":"ATENDIMENTO • OFFLINE"):(state.online?"ONLINE":"OFFLINE");$("mainMonitorStatus").textContent=state.active?(state.online?"Monitoramento ativo":"Monitoramento ativo • sem rede"):"Monitoramento inativo"}
setInterval(updateClock,1000);updateClock();
async function openDB(){return new Promise((resolve,reject)=>{if(state.db)return resolve(state.db);const req=indexedDB.open(CONFIG.dbName,CONFIG.dbVersion);req.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains(CONFIG.queueStore))db.createObjectStore(CONFIG.queueStore,{keyPath:"id",autoIncrement:true});if(!db.objectStoreNames.contains(CONFIG.eventStore))db.createObjectStore(CONFIG.eventStore,{keyPath:"id",autoIncrement:true})};req.onsuccess=e=>{state.db=e.target.result;resolve(state.db)};req.onerror=()=>reject(req.error)})}
async function queuePayload(payload,kind="registro"){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(CONFIG.queueStore,"readwrite");tx.objectStore(CONFIG.queueStore).add({payload,kind,createdAt:now().toISOString()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function getQueue(){try{const db=await openDB();return await new Promise((resolve,reject)=>{const r=db.transaction(CONFIG.queueStore,"readonly").objectStore(CONFIG.queueStore).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}catch{return[]}}
async function removeQueue(id){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(CONFIG.queueStore,"readwrite");tx.objectStore(CONFIG.queueStore).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function logEventLocal(name,data={}){try{const db=await openDB();db.transaction(CONFIG.eventStore,"readwrite").objectStore(CONFIG.eventStore).add({eventName:name,data,at:now().toISOString()})}catch{}}
async function postPayload(payload,{queueOnFail=true,silent=false}={}){const body=new URLSearchParams();Object.entries(payload).forEach(([k,v])=>{if(v!==undefined&&v!==null)body.append(k,String(v))});if(!navigator.onLine){if(queueOnFail)await queuePayload(payload);if(!silent)toast("Sem rede. Registro guardado no aparelho.");return{queued:true}}try{await fetch(CONFIG.urlApp,{method:"POST",mode:"no-cors",body});return{queued:false}}catch(err){if(queueOnFail)await queuePayload(payload);if(!silent)toast("Falha de rede. Registro guardado para sincronização.");return{queued:true,error:err}}}
async function syncQueue(){if(!navigator.onLine)return;for(const item of await getQueue()){try{const body=new URLSearchParams();Object.entries(item.payload||{}).forEach(([k,v])=>body.append(k,String(v)));await fetch(CONFIG.urlApp,{method:"POST",mode:"no-cors",body});await removeQueue(item.id)}catch{break}}updateMainKPIs()}
window.addEventListener("online",()=>{state.online=true;updateClock();toast("Conexão restabelecida. Sincronizando...");syncQueue()});window.addEventListener("offline",()=>{state.online=false;updateClock();if(state.active)recordAnomaly("NETWORK_LOST","Perda de conexão durante atendimento",false)});setInterval(syncQueue,30000);
function getPatio(){return JSON.parse(localStorage.getItem("rd_patio")||"[]")}function setPatio(v){localStorage.setItem("rd_patio",JSON.stringify(v));updateMainKPIs()}function addPatio(v){setPatio([...getPatio(),v])}function removePatio(id){setPatio(getPatio().filter(v=>v.idLocal!==id))}
async function updateMainKPIs(){const port=$("portaria").value;$("kpiPatio").textContent=getPatio().filter(v=>v.portaria===port).length;$("kpiFila").textContent=(await getQueue()).length}
function currentGps(){return state.lastPosition?`${state.lastPosition.coords.latitude}, ${state.lastPosition.coords.longitude}`:""}
function getFreshGps(){return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>{state.lastPosition=p;resolve(p)},reject,{enableHighAccuracy:true,timeout:15000,maximumAge:1000}))}
async function startMonitoring(){state.active=true;state.activeId=state.activeId||Date.now().toString();updateClock();if(!navigator.geolocation)throw new Error("GPS indisponível");await getFreshGps();state.watchId=navigator.geolocation.watchPosition(p=>state.lastPosition=p,()=>recordAnomaly("GPS_LOST","Perda de atualização de localização",true),{enableHighAccuracy:true,maximumAge:2500,timeout:15000});if(navigator.getBattery)navigator.getBattery().then(b=>state.battery=b).catch(()=>{})}
function stopMonitoring(){if(state.watchId!==null){navigator.geolocation.clearWatch(state.watchId);state.watchId=null}state.active=false;state.lastPosition=null;state.activeId=null;updateClock()}
async function recordAnomaly(type,details,critical=true){if(!state.active)return;const p={tipoRegistro:"ALERTA_ANOMALIA",idLocal:state.activeId||"",portaria:$("portaria").value,vigia:CONFIG.vigia,event:type,detalhes:details,localizacao:currentGps(),dataAtual:human().data,horaAtual:human().hora,critico:critical?"SIM":"NAO"};await logEventLocal(type,p);await postPayload(p,{silent:true});if(critical)toast("Anomalia registrada para averiguação.")}
document.addEventListener("visibilitychange",()=>{if(!state.active)return;if(document.hidden)state.pageHiddenAt=Date.now();else if(state.pageHiddenAt){const s=Math.round((Date.now()-state.pageHiddenAt)/1000);state.pageHiddenAt=null;if(s>=10)recordAnomaly("APP_BACKGROUND",`Aplicativo ficou em segundo plano por ${s}s`,false)}});
function saveOnboarding(){localStorage.setItem("rd_onboarding_slide",String(state.onboarding.slide));localStorage.setItem("rd_onboarding_done",String(state.onboarding.done));localStorage.setItem("rd_onboarding_logs",JSON.stringify(state.onboarding.logs))}
function showOnboardSlide(n){state.onboarding.slide=n;[1,2,3].forEach(i=>$("onboard"+i).classList.toggle("active",i===n));[1,2,3].forEach(i=>$("obp"+i).classList.toggle("active",i<=n));saveOnboarding()}
async function acceptSlide(n){state.onboarding.logs[`slide${n}`]=human().iso;await logEventLocal("ONBOARDING_ACCEPTED",{step:n});saveOnboarding()}
$("btnGatewayStart").onclick=()=>{if(state.onboarding.done){showView("viewMain");updateMainKPIs()}else{showView("viewOnboarding");showOnboardSlide(Math.min(3,Math.max(1,state.onboarding.slide||1)))}};
$("obNext1").onclick=async()=>{await acceptSlide(1);showOnboardSlide(2)};$("obNext2").onclick=async()=>{await acceptSlide(2);showOnboardSlide(3)};$("obFinalCheck").onchange=e=>$("obFinish").disabled=!e.target.checked;$("obFinish").onclick=async()=>{if(!$("obFinalCheck").checked)return;await acceptSlide(3);state.onboarding.done=true;saveOnboarding();showView("viewMain");updateMainKPIs()};$("btnProtocolo").onclick=()=>showView("viewProtocol");$("btnBackProtocol").onclick=()=>showView("viewMain");$("btnReplayProtocol").onclick=()=>{state.onboarding.done=false;state.onboarding.slide=1;$("obFinalCheck").checked=false;$("obFinish").disabled=true;saveOnboarding();showView("viewOnboarding");showOnboardSlide(1)};
function resetEntry(){$("entryForm").reset();state.manualUnlocked=false;state.ocrDocumentAttempted=false;state.ocrPlateAttempted=false;state.ocrDocumentSuccess=false;state.ocrPlateSuccess=false;state.fotoCarimbadaBase64="";state.selfieTakenAt=null;state.ocrBusy=false;$("manualEscapeArea").classList.add("hidden");$("ocrStatus").textContent="Aguardando tentativa de leitura.";["empresa","tipoVeiculo"].forEach(id=>$(id).disabled=false);["placaBau","placaCavalo","motorista","rg","cnh","ajudantes","materiais","observacoes"].forEach(id=>$(id).disabled=true);$("btnEntryNext1").disabled=true;$("btnEntryNext2").disabled=true;$("btnSaveEntry").disabled=true;$("previewCarimbo").style.display="none";$("previewCarimbo").src="";$("stepEntry1").classList.add("active");$("stepEntry2").classList.remove("active");$("stepEntry3").classList.remove("active");$("entryProgress").style.width="33%";$("tipoAcesso").value="terceiro";$("thirdPartyFields").classList.remove("hidden");$("fleetBranch").classList.add("hidden");updateVehicleTypeFields()}
function openCalco(callback){vibrar(25);openOverlay(`<h3>⚠️ Atenção</h3><p>Em conformidade com as normas disponíveis abaixo e para todos, somado à assinatura realizada na folha de termo físico, assumo e confirmo este termo de responsabilidade, garantindo pessoalmente que o veículo está <strong>COMPLETAMENTE PARADO</strong>, com o <strong>MOTOR DESLIGADO</strong> e o <strong>CALÇO NAS RODAS</strong> devidamente posicionado.</p><button id="modalConfirm" type="button" class="btn btn-primary">Confirmar</button><button id="modalCancel" type="button" class="btn btn-ghost">Cancelar Ação</button>`);$("modalConfirm").onclick=()=>{vibrar(60);closeOverlay();callback()};$("modalCancel").onclick=closeOverlay}
function openVistoria(callback,saida=false){const texto=saida?"📋 VISTORIA OBRIGATÓRIA: confirme a vistoria de saída conforme o procedimento da operação.":($("tipoVeiculo").value==="Veículo Pequeno"?"📋 VISTORIA OBRIGATÓRIA: confirme que vistoriou a FRENTE e a CARGA do veículo.":"📋 VISTORIA OBRIGATÓRIA: confirme que vistoriou APENAS A CABINE do caminhão.");openOverlay(`<h3>${saida?"VISTORIA DE SAÍDA":"VISTORIA DO VEÍCULO"}</h3><p>${texto}</p><label class="check-row"><input id="modalVistoriaCheck" type="checkbox"><span>☑️ CONFIRMO QUE A VISTORIA FOI REALIZADA.</span></label><button id="modalVistoriaGo" type="button" class="btn btn-primary" disabled>Continuar</button>`);$("modalVistoriaCheck").onchange=e=>$("modalVistoriaGo").disabled=!e.target.checked;$("modalVistoriaGo").onclick=()=>{closeOverlay();callback()}}
function normalizeText(s){return(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[|¦]/g,"I").replace(/[“”‘’`]/g,"")}
const STOP=new Set(["REPUBLICA","FEDERATIVA","BRASIL","MINISTERIO","INFRAESTRUTURA","TRANSITO","CONTRAN","CARTEIRA","NACIONAL","HABILITACAO","DETRAN","NOME","DOCUMENTO","IDENTIDADE","CPF","VALIDADE","LOCAL","DATA","ESTADO","GOVERNO","REGISTRO","ORGAO","EMISSOR","CATEGORIA","CONDUTOR","PERMISSAO","DIRECAO","NUMERO","RENACH","EXAME","ASSINATURA","FILIACAO","NASCIMENTO","BRASILEIRO","BRASILEIRA"]);
function extractLabeledValue(text,label,re){const lines=normalizeText(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);for(let i=0;i<lines.length;i++){if(lines[i].includes(label)){const same=lines[i].replace(label,"").replace(/[:\-]/g," ").trim();const m=same.match(re);if(m)return m[0];const next=(lines[i+1]||"").match(re);if(next)return next[0]}}return""}
function extractRG(text){const t=normalizeText(text);const labeled=extractLabeledValue(t,"RG",/\d{1,2}[. -]?\d{3}[. -]?\d{3}[- ]?[0-9X]/i);if(labeled)return labeled.replace(/[^0-9X]/g,"");const m=t.match(/\b\d{1,2}[. -]?\d{3}[. -]?\d{3}[- ]?[0-9X]\b/);return m?m[0].replace(/[^0-9X]/g,""):""}
function extractCNH(text){const t=normalizeText(text);const labeled=extractLabeledValue(t,"CNH",/\d{9,11}/);if(labeled&&labeled.length>=9)return labeled;const all=t.match(/\b\d{11}\b/g)||[];return all[0]||""}
function extractName(text){const lines=normalizeText(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean),c=[];for(const line of lines){const m=line.match(/^NOME\s*[:\-]?\s*(.+)$/);if(m&&m[1].length>=5)c.push(m[1].trim());const words=line.split(/\s+/);if(/[0-9]/.test(line)||line.length<8||words.length<2||words.length>7)continue;if(!/^[A-Z ]+$/.test(line)||words.some(w=>w.length<2)||words.some(w=>STOP.has(w)))continue;c.push(line)}return c.sort((a,b)=>b.length-a.length)[0]||""}
const PLATE={letters:{0:"O",1:"I",2:"Z",5:"S",6:"G",7:"T",8:"B"},numbers:{O:"0",Q:"0",D:"0",I:"1",L:"1",Z:"2",S:"5",G:"6",T:"7",B:"8"}};
function repairMercosul(raw){const p=normalizeText(raw).replace(/[^A-Z0-9]/g,"").slice(0,7).split("");if(p.length!==7)return"";for(let i=0;i<3;i++)if(/\d/.test(p[i]))p[i]=PLATE.letters[p[i]]||p[i];if(/[A-Z]/.test(p[3]))p[3]=PLATE.numbers[p[3]]||p[3];if(/\d/.test(p[4])&&PLATE.letters[p[4]])p[4]=PLATE.letters[p[4]];for(const i of [5,6])if(/[A-Z]/.test(p[i]))p[i]=PLATE.numbers[p[i]]||p[i];const out=p.join("");return/^[A-Z]{3}\d[A-Z]\d{2}$/.test(out)?out:""}
function plateCandidates(text){const t=normalizeText(text).replace(/[^A-Z0-9\n]/g," "),out=[];for(const line of t.split(/\n+/)){const s=line.replace(/\s/g,"");for(let i=0;i<=s.length-7;i++){const c=s.slice(i,i+7),merc=repairMercosul(c);if(merc)out.push(merc);if(/^[A-Z]{3}\d{4}$/.test(c))out.push(c)} }return[...new Set(out)]}
function resizeCanvas(img,max=2400){const sc=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),cv=document.createElement("canvas");cv.width=Math.max(1,Math.round(img.naturalWidth*sc));cv.height=Math.max(1,Math.round(img.naturalHeight*sc));cv.getContext("2d").drawImage(img,0,0,cv.width,cv.height);return cv}
function imageFromFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function enhanceCanvas(src,{scale=1,gray=true,contrast=1.35,brightness=1}={}){const cv=document.createElement("canvas");cv.width=Math.max(1,Math.round(src.width*scale));cv.height=Math.max(1,Math.round(src.height*scale));const c=cv.getContext("2d");c.filter=`${gray?"grayscale(100%) ":""}contrast(${contrast}) brightness(${brightness})`;c.drawImage(src,0,0,cv.width,cv.height);return cv}
function getBounds(result,cv){const words=(result?.data?.words||[]).filter(w=>w.text&&w.bbox);if(!words.length)return null;const xs=words.map(w=>w.bbox.x0),ys=words.map(w=>w.bbox.y0),xe=words.map(w=>w.bbox.x1),ye=words.map(w=>w.bbox.y1),px=Math.round(cv.width*.03),py=Math.round(cv.height*.03),x=Math.max(0,Math.min(...xs)-px),y=Math.max(0,Math.min(...ys)-py),x2=Math.min(cv.width,Math.max(...xe)+px),y2=Math.min(cv.height,Math.max(...ye)+py);return{x,y,w:Math.max(1,x2-x),h:Math.max(1,y2-y)}}
function cropCanvas(cv,b){if(!b)return cv;const out=document.createElement("canvas");out.width=Math.max(1,Math.round(b.w));out.height=Math.max(1,Math.round(b.h));out.getContext("2d").drawImage(cv,b.x,b.y,b.w,b.h,0,0,out.width,out.height);return out}
async function ocrRun(canvas,mode,psm=6){if(!window.Tesseract)throw new Error("OCR indisponível");const worker=await Tesseract.createWorker("por");try{const params={tessedit_pageseg_mode:String(psm)};if(mode==="placa")params.tessedit_char_whitelist="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";await worker.setParameters(params);return await worker.recognize(canvas)}finally{await worker.terminate()}}
async function processarOcr(file,tipo){if(!file||state.ocrBusy)return;state.ocrBusy=true;const doc=tipo==="documento";if(doc)state.ocrDocumentAttempted=true;else state.ocrPlateAttempted=true;setLoading("LENDO IMAGEM",doc?"Tentando leitura integral, área útil e pré-processamentos diferentes.":"Tentando leitura da placa com diferentes ajustes e correção das confusões mais comuns do OCR.");try{const img=await imageFromFile(file),full=resizeCanvas(img),texts=[];let scout=null;try{scout=await ocrRun(full,doc?"documento":"placa",doc?11:7);texts.push(scout.data.text||"")}catch{}if(doc&&scout){const b=getBounds(scout,full);if(b){const crop=cropCanvas(full,b);for(const variant of [enhanceCanvas(crop,{gray:false,contrast:1.1,scale:1.35}),enhanceCanvas(crop,{gray:true,contrast:1.7,scale:1.6}),enhanceCanvas(crop,{gray:true,contrast:2.1,scale:1.9,brightness:1.08})]){try{texts.push((await ocrRun(variant,"documento",6)).data.text||"")}catch{}}}}else if(!doc){for(const variant of [enhanceCanvas(full,{gray:false,contrast:1.1,scale:1.2}),enhanceCanvas(full,{gray:true,contrast:1.6,scale:1.5}),enhanceCanvas(full,{gray:true,contrast:2.0,scale:1.8,brightness:1.08})]){try{texts.push((await ocrRun(variant,"placa",7)).data.text||"")}catch{}}}const text=texts.join("\n");if(doc){const nome=extractName(text),rg=extractRG(text),cnh=extractCNH(text);if(nome)$('motorista').value=nome;if(rg)$('rg').value=rg;if(cnh)$('cnh').value=cnh;state.ocrDocumentSuccess=Boolean(nome||rg||cnh);$("ocrStatus").textContent=state.ocrDocumentSuccess?`✅ Documento processado. ${nome?"Nome identificado. ":""}${rg?"RG identificado. ":""}${cnh?"CNH identificada.":""}`:"⚠️ OCR processou a imagem, mas não encontrou dados confiáveis."}else{const candidatos=plateCandidates(text),placa=candidatos[0]||"";if(placa)$("placaBau").value=placa;state.ocrPlateSuccess=Boolean(placa);$("ocrStatus").textContent=placa?`✅ Placa identificada: ${placa}`:"⚠️ Nenhuma placa válida foi encontrada."}if((doc&&state.ocrDocumentSuccess)||(!doc&&state.ocrPlateSuccess)){unlockEntryFields();if(doc)openVistoria(()=>updateEntryButton());else updateEntryButton()}else{$("manualEscapeArea").classList.remove("hidden");updateEntryButton()}vibrar([70,40,70])}catch(err){$("ocrStatus").textContent="❌ Falha técnica na leitura. O modo manual foi liberado e o evento será marcado para conferência.";$("manualEscapeArea").classList.remove("hidden");updateEntryButton();toast("Falha real na leitura. Modo manual disponível")}finally{state.ocrBusy=false;closeOverlay()}}
function unlockEntryFields(){state.manualUnlocked=true;["empresa","tipoVeiculo","placaBau","placaCavalo","motorista","rg","cnh","ajudantes","materiais","observacoes"].forEach(id=>$(id).disabled=false);updateVehicleTypeFields()}
function updateVehicleTypeFields(){const truck=$("tipoVeiculo").value==="Caminhões & Carretas";$("cavaloWrap").classList.toggle("hidden",!truck);$("placaCavalo").required=truck;$("lblPlacaBau").textContent=truck?"PLACA DO BAÚ DO CAVALO *":"PLACA DO VEÍCULO *";$("lblVistoria").textContent=truck?"☑️ CONFIRMO QUE VISTORIEI APENAS A CABINE DO CAMINHÃO.":"☑️ CONFIRMO QUE VISTORIEI A FRENTE E A CARGA DO VEÍCULO."}
function updateEntryButton(){const empresa=$("empresa").value.trim(),placa=$("placaBau").value.trim(),mot=$("motorista").value.trim(),truck=$("tipoVeiculo").value==="Caminhões & Carretas",cavalo=!truck||$("placaCavalo").value.trim().length>=6,photoFlow=state.ocrDocumentAttempted||state.ocrPlateAttempted;$("btnEntryNext1").disabled=!(state.manualUnlocked&&empresa.length>=2&&placa.length>=6&&mot.length>=2&&cavalo&&photoFlow)}
["empresa","placaBau","placaCavalo","motorista"].forEach(id=>$(id).addEventListener("input",updateEntryButton));$("tipoVeiculo").addEventListener("change",()=>{updateVehicleTypeFields();updateEntryButton()});
$("btnOcrDocumento").onclick=()=>$("fileDocumento").click();$("btnOcrPlaca").onclick=()=>$("filePlacaBau").click();$("fileDocumento").onchange=e=>processarOcr(e.target.files[0],"documento");$("filePlacaBau").onchange=e=>processarOcr(e.target.files[0],"placa");
$("btnManualEscape").onclick=()=>{openOverlay(`<h3>⚠️ MODO MANUAL</h3><p>A tentativa por imagem não produziu dados utilizáveis. O preenchimento manual será liberado e o registro ficará marcado para conferência.</p><button id="confirmManual" type="button" class="btn btn-primary">Ciente e liberar</button>` ,"danger");$("confirmManual").onclick=()=>{unlockEntryFields();closeOverlay();toast("Modo manual liberado e registrado.")}};
$("btnNovo").onclick=()=>{resetEntry();openCalco(async()=>{try{setLoading("ATIVANDO ATENDIMENTO","Solicitando localização…");state.activeId=Date.now().toString();await startMonitoring();closeOverlay();$("btnOcrDocumento").disabled=false;$("btnOcrPlaca").disabled=false;showView("viewEntry");$("ocrStatus").textContent="Pronto para leitura. A foto vem primeiro."}catch{closeOverlay();openOverlay(`<h3>GPS NECESSÁRIO</h3><p>Não foi possível obter a localização do aparelho. Autorize o GPS e tente novamente.</p><button id="gpsRetry" class="btn btn-primary" type="button">Tentar novamente</button><button id="gpsCancel" class="btn btn-ghost" type="button">Cancelar</button>`);$("gpsRetry").onclick=()=>{closeOverlay();$("btnNovo").click()};$("gpsCancel").onclick=()=>{closeOverlay();stopMonitoring()}}})};
$("tipoAcesso").onchange=()=>{const fleet=$("tipoAcesso").value==="frota";$("thirdPartyFields").classList.toggle("hidden",fleet);$("fleetBranch").classList.toggle("hidden",!fleet)};$("btnFleetBack").onclick=()=>{$("tipoAcesso").value="terceiro";$("tipoAcesso").dispatchEvent(new Event("change"))};$("btnFleetGate").onclick=async()=>{await postPayload({tipoRegistro:"LIBERACAO_FROTA_INTERNA",portaria:$("portaria").value,vigia:CONFIG.vigia,dataAtual:human().data,horaAtual:human().hora});toast("Portão liberado para frota própria.");showView("viewMain")};
$("btnDevTest").onclick=()=>{state.manualUnlocked=true;state.ocrDocumentAttempted=true;$("empresa").value="EMPRESA TESTE";$("tipoVeiculo").value="Veículo Pequeno";$("placaBau").value="XXX9999";$("motorista").value="Motorista Teste";$("rg").value="MG10200300";unlockEntryFields();updateVehicleTypeFields();updateEntryButton();toast("Modo DEV ativado. Campos preenchidos e liberados.")};
$("btnEntryNext1").onclick=()=>{if($("tipoVeiculo").value==="Caminhões & Carretas"&&!$("placaCavalo").value.trim())return toast("Informe a placa do cavalo.");$("stepEntry1").classList.remove("active");$("stepEntry2").classList.add("active");$("entryProgress").style.width="66%"};$("chkVistoria").onchange=e=>$("btnEntryNext2").disabled=!e.target.checked;$("btnEntryBack2").onclick=()=>{$("stepEntry2").classList.remove("active");$("stepEntry1").classList.add("active");$("entryProgress").style.width="33%"};$("btnEntryNext2").onclick=()=>{if(!$('chkVistoria').checked)return toast("A vistoria precisa ser confirmada.");$("sumPortaria").textContent=$("portaria").value;$("sumVeiculo").textContent=$("tipoVeiculo").value;$("sumPlaca").textContent=$("placaBau").value.toUpperCase();$("sumMotorista").textContent=$("motorista").value.toUpperCase();$("stepEntry2").classList.remove("active");$("stepEntry3").classList.add("active");$("entryProgress").style.width="100%"};$("btnEntryBack3").onclick=()=>{$("stepEntry3").classList.remove("active");$("stepEntry2").classList.add("active");$("entryProgress").style.width="66%"};
$("btnSelfie").onclick=()=>$("fileSelfie").click();$("fileSelfie").onchange=e=>gerarCarimbo(e.target.files[0]);async function gerarCarimbo(file){if(!file)return;setLoading("GERANDO CARIMBO","Preparando a selfie de confirmação…");try{const img=await imageFromFile(file),maxW=1000,sc=Math.min(1,maxW/img.naturalWidth),w=Math.round(img.naturalWidth*sc),h=Math.round(img.naturalHeight*sc),cv=$("canvasCarimbo"),pad=145;cv.width=w;cv.height=h+pad;const c=cv.getContext("2d");c.drawImage(img,0,0,w,h);c.fillStyle="rgba(10,12,15,.86)";c.fillRect(0,h,w,pad);const g=currentGps()||"GPS indisponível",n=human(),lines=["ROMANEIO DIGITAL • CONFIRMAÇÃO","VIGIA: "+CONFIG.vigia.toUpperCase(),"EMPRESA: "+$("empresa").value.toUpperCase(),"VEÍCULO: "+$("tipoVeiculo").value.toUpperCase(),"PLACA: "+$("placaBau").value.toUpperCase(),$("placaCavalo").value.trim()?"PLACA CAVALO: "+$("placaCavalo").value.toUpperCase():"","MOTORISTA: "+$("motorista").value.toUpperCase(),"PORTARIA: "+$("portaria").value,"GPS: "+g,"DATA/HORA: "+n.data+" "+n.hora].filter(Boolean);let y=h+20;lines.forEach((line,i)=>{c.font=i===0?"700 14px Arial":"11px Arial";c.fillStyle=i===0?"#d4af37":"#eef0f3";c.fillText(line,16,y);y+=12;i===0&&(y+=4)});state.fotoCarimbadaBase64=cv.toDataURL("image/jpeg",.66);$("previewCarimbo").src=state.fotoCarimbadaBase64;$("previewCarimbo").style.display="block";state.selfieTakenAt=n.iso;$("btnSaveEntry").disabled=false;toast("Selfie carimbada pronta.")}catch{toast("Não foi possível gerar a selfie carimbada.")}finally{closeOverlay()}}
$("entryForm").onsubmit=async e=>{e.preventDefault();if(!$('chkVistoria').checked)return toast("Confirme a vistoria.");if(!state.fotoCarimbadaBase64)return toast("Faça a selfie de confirmação.");await salvarEntrada()};async function salvarEntrada(){try{setLoading("SALVANDO ENTRADA","Registrando a operação…");const gps=await getFreshGps().catch(()=>state.lastPosition),h=human(),obj={idLocal:state.activeId,tipoRegistro:"Entrada",portaria:$("portaria").value,empresa:$("empresa").value.trim(),tipoVeiculo:$("tipoVeiculo").value,placaCavalo:$("placaCavalo").value.trim().toUpperCase(),placaBau:$("placaBau").value.trim().toUpperCase(),motorista:$("motorista").value.trim(),rg:$("rg").value.trim(),cnh:$("cnh").value.trim(),ajudantes:$("ajudantes").value.trim(),materiais:$("materiais").value.trim(),localizacao:gps?`${gps.coords.latitude},${gps.coords.longitude}`:currentGps(),observacoes:$("observacoes").value.trim()||"OK",vigia:CONFIG.vigia,dataAtual:h.data,horaAtual:h.hora,calcoConfirmado:"SIM",vistoriaConfirmada:"SIM",modoRegistro:state.manualUnlocked&&(!state.ocrDocumentSuccess||!state.ocrPlateSuccess)?"Manual / OCR falhou":"OCR / App Web",sinal:state.online?"ONLINE":"OFFLINE",fotoValidacao:state.fotoCarimbadaBase64,selfieTakenAt:state.selfieTakenAt||h.iso};addPatio({idLocal:obj.idLocal,portaria:obj.portaria,empresa:obj.empresa,tipoVeiculo:obj.tipoVeiculo,placaBau:obj.placaBau,placaCavalo:obj.placaCavalo,motorista:obj.motorista,horaAtual:obj.horaAtual,dataAtual:obj.dataAtual});await postPayload(obj);stopMonitoring();resetEntry();closeOverlay();showView("viewMain");updateMainKPIs();toast("✅ Entrada registrada.")}catch{closeOverlay();toast("Falha ao salvar. O registro foi preservado para sincronização.")}}
async function cancelActive(stage){openOverlay(`<h3>Cancelar atendimento</h3><p>Informe o motivo para registrar o encerramento normal do atendimento.</p><div class="field"><label for="cancelReason">MOTIVO</label><textarea id="cancelReason"></textarea></div><button id="confirmCancel" type="button" class="btn btn-primary">Cancelar registro</button><button id="cancelCancel" type="button" class="btn btn-ghost">Voltar</button>`);$("confirmCancel").onclick=async()=>{const reason=$("cancelReason").value.trim();if(reason.length<3)return toast("Informe o motivo.");await postPayload({tipoRegistro:"Cancelamento",idLocal:state.activeId||"",portaria:$("portaria").value,vigia:CONFIG.vigia,etapa:stage,motivoCancelamento:reason,dataAtual:human().data,horaAtual:human().hora,localizacao:currentGps()});stopMonitoring();resetEntry();closeOverlay();showView("viewMain");toast("Atendimento cancelado com segurança.")};$("cancelCancel").onclick=closeOverlay}
["btnCancelEntry1","btnCancelEntry2","btnCancelEntry3"].forEach(id=>$(id).onclick=()=>cancelActive("ENTRADA"));
$("btnDocas").onclick=()=>{renderDocks();showView("viewDocks")};$("btnBackMainDocks").onclick=()=>showView("viewMain");function escapeHtml(s){return String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function renderDocks(){const list=getPatio().filter(v=>v.portaria===$("portaria").value),el=$("dockList");if(!list.length){el.innerHTML='<div class="empty">Nenhum veículo aguardando saída nesta portaria.</div>';return}el.innerHTML="";list.forEach(v=>{const div=document.createElement("div");div.className="vehicle-card";div.innerHTML=`<div class="vehicle-main">${escapeHtml(v.placaBau||"-")} • ${escapeHtml(v.motorista||"-")}</div><div class="vehicle-meta">${escapeHtml(v.empresa||"")}<br>${escapeHtml(v.tipoVeiculo||"")} ${v.placaCavalo?`• Cavalo: ${escapeHtml(v.placaCavalo)}`:""}<br>Entrada: ${escapeHtml(v.horaAtual||"-")}</div><button class="btn btn-primary" type="button">Liberar saída</button>`;div.querySelector("button").onclick=()=>openExit(false,v);el.appendChild(div)})}
$("btnManualExit").onclick=()=>openExit(true,null);
async function openExit(manual,vehicle){state.exitContext=vehicle;$("exitManual").value=manual?"true":"false";$("exitId").value=manual?"":(vehicle?.idLocal||"");$("manualExitWrap").classList.toggle("hidden",!manual);$("manualPlate").value="";$("chkVistoriaSaida").checked=false;$("btnSaveExit").disabled=true;$("exitSummary").innerHTML=vehicle?`<div class="summary-item"><small>Empresa</small><strong>${escapeHtml(vehicle.empresa)}</strong></div><div class="summary-item"><small>Placa</small><strong>${escapeHtml(vehicle.placaBau)}</strong></div><div class="summary-item"><small>Motorista</small><strong>${escapeHtml(vehicle.motorista)}</strong></div><div class="summary-item"><small>Entrada</small><strong>${escapeHtml(vehicle.horaAtual)}</strong></div>`:'<div class="banner">Informe a placa e o sistema tentará localizar a entrada correspondente.</div>';openCalco(async()=>{try{state.activeId=$("exitId").value||Date.now().toString();setLoading("ATIVANDO SAÍDA","Solicitando localização…");await startMonitoring();closeOverlay();openVistoria(()=>{showView("viewExit");$("chkVistoriaSaida").checked=true;updateExitSaveButton()},true)}catch{closeOverlay();stopMonitoring();toast("GPS obrigatório para registrar a saída.")}})}
function updateExitSaveButton(){const manual=$("exitManual").value==="true",plateOk=!manual||$("manualPlate").value.trim().length>=6;$("btnSaveExit").disabled=!(plateOk&&$("chkVistoriaSaida").checked)}$("chkVistoriaSaida").onchange=updateExitSaveButton;$("manualPlate").oninput=updateExitSaveButton;$("btnCancelExit").onclick=()=>{stopMonitoring();showView("viewDocks");renderDocks()};$("btnSaveExit").onclick=async()=>{if(!$('chkVistoriaSaida').checked)return toast("Confirme a vistoria de saída.");await salvarSaida()};
async function salvarSaida(){try{setLoading("SALVANDO SAÍDA","Registrando hora e localização…");const manual=$("exitManual").value==="true",plate=(manual?$("manualPlate").value:state.exitContext?.placaBau||"").trim().toUpperCase(),h=human(),payload={idLocal:$("exitId").value||"",tipoRegistro:"Saida",isManual:manual?"true":"false",portaria:$("portaria").value,placaBau:plate,empresa:state.exitContext?.empresa||"",motorista:state.exitContext?.motorista||"",tipoVeiculo:state.exitContext?.tipoVeiculo||"",placaCavalo:state.exitContext?.placaCavalo||"",localizacao:currentGps(),vigia:CONFIG.vigia,dataAtual:h.data,horaAtual:h.hora,calcoConfirmado:"SIM (SAÍDA)",vistoriaConfirmada:"SIM (SAÍDA)",modoRegistro:manual?"Manual / Órfã":"Saída Expressa"};await postPayload(payload);if(!manual&&state.exitContext?.idLocal)removePatio(state.exitContext.idLocal);else{const found=getPatio().find(v=>v.placaBau===plate&&v.portaria===$("portaria").value);if(found)removePatio(found.idLocal)}stopMonitoring();closeOverlay();showView("viewDocks");renderDocks();toast("✅ Saída registrada.")}catch{closeOverlay();stopMonitoring();showView("viewDocks");toast("Saída preservada para sincronização.")}}
$("portaria").onchange=updateMainKPIs;window.addEventListener("load",async()=>{try{await openDB()}catch{}updateMainKPIs();syncQueue()});
